name: Test & Build

on:
  pull_request:
    branches: [ "prod" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]
    services:

      postgres:
        # Docker Hub image
        image: postgres
        env:
          POSTGRES_USERNAME: postgres_test
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      env:
        DB_HOST: localhost
        DB_PORT: 5432
        DB_PASSWORD: password
        DB_NAME: postgres
        DB_USERNAME: postgres_test
        SECRET_KEY: unsecure-secretkeykeyekekeyeyeyeyeyeyeyeyeyeyeyeyeyeye129
        ALGORITHM: HS256
        ACCESS_TOKEN_EXPIRE_MINUTES: 60
        ENVIRONNEMENT: test
        TEST_MODEL_PATH: ./app/statics/model/
        TEST_TOKEN_PATH: ./app/statics/tokenizer/
        ALLOWED_ORIGINS: http://127.0.0.1:8000, http://127.0.0.1:9090

    steps:

      - uses: actions/checkout@v4 # checkout repo

      - name: Set up Python ${{ matrix.python-version }} 
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Tests
        run: python -m pytest tests/

  build-and-push:
    runs-on: ubuntu-latest
    needs: test  

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3  
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_APPNAME }}:webapp .

      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_APPNAME }}:webapp